version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
